// <auto-generated />
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataModel.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180331085013_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("DataModel.ListItem", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Des");

                    b.Property<DateTimeOffset>("DueDate");

                    b.Property<byte[]>("Icon");

                    b.Property<bool>("IsCheck");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ListId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DataModel.TempState", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Des");

                    b.Property<DateTimeOffset>("DueDate");

                    b.Property<byte[]>("Icon");

                    b.Property<int>("ListIndex");

                    b.Property<string>("Title");

                    b.HasKey("ListId");

                    b.ToTable("State");
                });
#pragma warning restore 612, 618
        }
    }
}
